Fixed missing response argument in get_context (#1570)
get_context expects a response as well.  If this is missing when running the example you'll get `TypeError: get_context() got an unexpected keyword argument 'response'`.  I've added this to the get_context signature here and things should work.  Thanks for the great library!  It's awesome!