Fix missing return annotation in get_customer docs
Using the documentation as-is produces this error:
```
MissingReturnAnnotationError: Return annotation missing for field "get_customer", did you forget to add it?
```