Add implicit default value for nullable input fields
Prior to this change, parsing a partial input object resulted in a
TypeError: InputType is missing required keyword-only argument arg.
Now, we use None as an implicit default value for nullable fields,
making them optional.

According to the GraphQL spec, nullable fields are always optional.
See https://spec.graphql.org/draft/#sec-Non-Null.Nullable-vs-Optional